# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MessageBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_MessageBox(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(452, 271)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 451, 271))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("res/background.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(30, 30, 391, 211))
        self.tabWidget.setStyleSheet("QTabWidget::pane{\n"
"min-width:70px;\n"
"min-height:25px;\n"
"border-top: 1px solid;\n"
"border-color: white;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"\n"
"min-width:110px;\n"
"\n"
"min-height:25px;\n"
"\n"
"color: white;\n"
"\n"
"font: 57 14pt \"Alibaba PuHuiTi\";\n"
"\n"
"border: 0px solid;\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"QTabBar::tab:selected{\n"
"\n"
"min-width:390px;\n"
"\n"
"min-height:25px;\n"
"color: white;\n"
"\n"
"font: 57 16pt \"Alibaba PuHuiTi\";\n"
"\n"
"border: 0px solid;\n"
"\n"
"border-bottom: 5px solid;\n"
"\n"
"border-color: #4796f0;\n"
"\n"
"}\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.label_20 = QtWidgets.QLabel(self.tab_15)
        self.label_20.setGeometry(QtCore.QRect(10, 20, 371, 101))
        font = QtGui.QFont()
        font.setFamily("Alibaba PuHuiTi")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_20.setFont(font)
        self.label_20.setAutoFillBackground(False)
        self.label_20.setStyleSheet("color: white;\n"
"font: 57 14pt \"Alibaba PuHuiTi\";")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_15)
        self.pushButton_4.setGeometry(QtCore.QRect(320, 130, 61, 41))
        self.pushButton_4.setStyleSheet("QPushButton {    \n"
"    color: white;\n"
"    font: 57 12pt \"Alibaba PuHuiTi\";\n"
"    background-color: rgb(107, 146, 255);\n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover {\n"
"    color: black;\n"
"    background-color: rgb(129, 162, 255)\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(107, 146, 255);\n"
"    color: white;\n"
"}\n"
"border-image: url(:/button/button_unselected.png);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget.addTab(self.tab_15, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.pushButton_4.clicked.connect(self.closeWindow)



    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_20.setText(_translate("Form", ""))
        self.pushButton_4.setText(_translate("Form", "确定"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_15), _translate("Form", "提示"))

    def closeWindow(self):
        # 关闭当前窗口
        self.close()
